<main>
<section class="knowledge-hero"><div class="container"><div class="row align-items-center gy-5"><div class="col-lg-7" data-aos="fade-up"><nav class="inner-breadcrumb"><a href="<?= e(frontend_url('index.php')) ?>">Trang chủ</a><i class="fa-solid fa-angle-right"></i><span>Kiến thức</span></nav><span class="section-kicker">KIẾN THỨC THỰC DỤNG</span><h1>Website, SEO và vận hành số cho doanh nghiệp</h1><p>Nội dung tập trung vào cách lựa chọn, xây dựng và duy trì website hiệu quả; không viết chỉ để đủ số lượng bài.</p></div><div class="col-lg-5"><div class="knowledge-search"><i class="fa-solid fa-magnifying-glass"></i><input type="search" id="articleSearch" placeholder="Tìm bài viết..."><small>Tìm theo tiêu đề, mô tả hoặc danh mục</small></div></div></div></div></section>
<section class="knowledge-categories"><div class="container"><div class="knowledge-categories__track"><button class="is-active" data-article-category="all">Tất cả</button><button data-article-category="thiet-ke-website">Thiết kế website</button><button data-article-category="seo">SEO website</button><button data-article-category="van-hanh">Vận hành</button><button data-article-category="noi-dung">Nội dung số</button></div></div></section>
<section class="section section--light"><div class="container"><div class="knowledge-toolbar"><div><span class="section-kicker">BÀI VIẾT MỚI</span><h2><strong id="articleCount"><?= count($articleItems) ?></strong> bài viết</h2></div><select class="form-select" id="articleSort"><option value="featured">Nổi bật</option><option value="newest">Mới nhất</option><option value="title">Tên A - Z</option></select></div><div class="article-list-grid" id="articleList">
<?php foreach ($articleItems as $article): ?><article class="knowledge-card" data-category="<?= e($article['category']) ?>" data-featured="<?= e($article['featured']) ?>" data-title="<?= e($article['title']) ?>" data-search="<?= e($article['title'].' '.$article['excerpt'].' '.$article['category_label']) ?>"><a class="knowledge-card__image" href="<?= e(article_url($article)) ?>"><img src="<?= e($article['image_url']) ?>" alt="<?= e($article['title']) ?>" loading="lazy"><span><?= e($article['category_label']) ?></span></a><div class="knowledge-card__body"><div class="knowledge-card__meta"><span><i class="fa-regular fa-calendar"></i> <?= e($article['published_at']) ?></span><span><i class="fa-regular fa-clock"></i> <?= e($article['read_time']) ?></span></div><h3><a href="<?= e(article_url($article)) ?>"><?= e($article['title']) ?></a></h3><p><?= e($article['excerpt']) ?></p><a class="text-link" href="<?= e(article_url($article)) ?>">Đọc bài viết <i class="fa-solid fa-arrow-right"></i></a></div></article><?php endforeach; ?>
</div><div class="article-empty d-none" id="articleEmpty"><i class="fa-regular fa-folder-open"></i><h3>Không tìm thấy bài viết</h3><p>Hãy thử một từ khóa hoặc danh mục khác.</p></div></div></section>
<section class="newsletter-section"><div class="container"><div class="newsletter-box"><div><span class="section-kicker section-kicker--gold">NỘI DUNG MỚI</span><h2>Nhận tư vấn theo đúng bài toán doanh nghiệp</h2><p>Không cần đăng ký nhận email trong bản demo. Nút này dẫn thẳng tới trang liên hệ để trao đổi nhu cầu thực tế.</p></div><a class="btn btn-warning btn-lg" href="<?= e(frontend_url('lien-he.php')) ?>">Trao đổi với WebApp Bắc Ninh</a></div></div></section>
</main>

