<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>FreshAir S8 — Không khí sạch, cuộc sống tốt đẹp hơn | FreshAir Mall</title>
    <meta name="description" content="Máy lọc không khí FreshAir S8: HEPA H13, lọc 360°, vận hành êm ái. Giá ưu đãi 3.590.000đ, freeship toàn quốc, quà tặng và bảo hành 24 tháng.">
    <meta name="theme-color" content="#086b36">
    <link rel="canonical" href="{{ route('landing.freshair') }}">
    <link rel="icon" type="image/svg+xml" href="{{ asset('landing/purehome/leaf.svg') }}">
    <link rel="image_src" href="{{ asset('landing/freshair/share.jpg') }}">
    <meta property="og:locale" content="vi_VN">
    <meta property="og:type" content="website">
    <meta property="og:site_name" content="FreshAir Mall">
    <meta property="og:title" content="FreshAir S8 — Không khí sạch, cuộc sống tốt đẹp hơn">
    <meta property="og:description" content="Chỉ 3.590.000đ · Giảm 40% · Màng lọc HEPA H13 · Freeship toàn quốc · Bảo hành 24 tháng.">
    <meta property="og:url" content="{{ route('landing.freshair') }}">
    <meta property="og:image" content="{{ asset('landing/freshair/share.jpg') }}">
    <meta property="og:image:secure_url" content="{{ secure_asset('landing/freshair/share.jpg') }}">
    <meta property="og:image:type" content="image/jpeg">
    <meta property="og:image:width" content="1730">
    <meta property="og:image:height" content="909">
    <meta property="og:image:alt" content="FreshAir S8 — Không khí sạch cho cuộc sống tốt đẹp hơn, giá 3.590.000đ">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="FreshAir S8 — Không khí sạch, cuộc sống tốt đẹp hơn">
    <meta name="twitter:description" content="Giá ưu đãi 3.590.000đ, giảm 40%. Freeship toàn quốc, quà tặng và bảo hành 24 tháng.">
    <meta name="twitter:image" content="{{ asset('landing/freshair/share.jpg') }}">
    <meta name="twitter:image:alt" content="Máy lọc không khí FreshAir S8 và ưu đãi 3.590.000đ">
    <link rel="preload" as="image" href="{{ asset('landing/freshair/hero.webp') }}" fetchpriority="high">
    <link rel="stylesheet" href="{{ asset('vendor/swiper/swiper-bundle.min.css') }}">
    @vite(['resources/css/landing/freshair.css', 'resources/js/landing/freshair.js'])
</head>
<body class="freshair">
    @php
        $gallery = [
            ['living', 'Sản phẩm trong phòng khách', 'Tô điểm không gian hiện đại'],
            ['display', 'Cận cảnh màn hình cảm ứng', 'Theo dõi chất lượng không khí'],
            ['filter', 'Bộ lọc bên trong', 'Màng lọc HEPA H13 cao cấp'],
            ['bedroom', 'Trong phòng ngủ', 'Vận hành êm ái, giấc ngủ sâu hơn'],
            ['family', 'Gia đình sử dụng', 'Không khí sạch cho cả nhà'],
            ['office', 'Góc làm việc sạch thoáng', 'Tập trung hơn, thoải mái hơn'],
        ];
        $productGallery = array_merge([['product', 'Máy lọc không khí FreshAir S8', '']], $gallery);
    @endphp
    <a class="fa-skip" href="#noi-dung">Đến nội dung chính</a>
    <div class="fa-sale-banner" id="trang-chu"><div class="fa-container"><x-landing.purehome-icon name="bolt" /><strong>SIÊU SALE HÔM NAY</strong><span class="fa-sale-dot">•</span><b>GIẢM ĐẾN <em>40%</em></b><span class="fa-sale-dot">•</span><b><em>FREESHIP</em> TOÀN QUỐC</b><a href="#uu-dai">Khám phá ưu đãi <x-landing.purehome-icon name="arrow" /></a></div></div>
    <header class="fa-header">
        <div class="fa-container fa-header-main">
            <a class="fa-brand" href="#trang-chu" aria-label="FreshAir Mall — Trang chủ"><x-landing.purehome-icon name="leaf" /><span><strong>FreshAir Mall</strong><small>Không khí sạch. Cuộc sống xanh</small></span></a>
            <form class="fa-search" role="search"><label class="fa-sr-only" for="fa-search-input">Tìm thông tin về FreshAir S8</label><input id="fa-search-input" type="search" placeholder="Bạn muốn tìm thông tin gì về FreshAir S8?" autocomplete="off"><button type="submit" aria-label="Tìm kiếm"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><circle cx="10" cy="10" r="6.5"/><path d="m15 15 6 6"/></svg></button></form>
            <a class="fa-hotline" href="tel:1900636888"><x-landing.purehome-icon name="phone" /><span><small>Hotline tư vấn</small><strong>1900 636 888</strong><small>(8:00 - 22:00)</small></span></a>
            <button class="fa-cart-button" type="button" data-open-cart aria-label="Mở giỏ hàng"><x-landing.purehome-icon name="cart" /><span>Giỏ hàng</span><b data-cart-count>0</b></button>
        </div>
    </header>
    <main id="noi-dung">
        <section class="fa-hero" aria-labelledby="fa-hero-title">
            <div class="fa-container fa-hero-layout">
                <div class="fa-hero-scene">
                    <img class="fa-hero-image" src="{{ asset('landing/freshair/hero.webp') }}" alt="Máy lọc FreshAir S8 trong căn phòng ngập ánh sáng và cây xanh" width="1792" height="768" fetchpriority="high">
                    <div class="fa-hero-copy"><p class="fa-hero-kicker">Hít thở sạch hơn. Sống khỏe hơn.</p><h1 id="fa-hero-title"><em>Không khí sạch</em><br>Cho cuộc sống<br>tốt đẹp hơn <x-landing.purehome-icon name="leaf" /></h1><p><strong>Bảo vệ sức khỏe gia đình bạn</strong><br>mỗi ngày với FreshAir S8.</p><div class="fa-hero-icons">@foreach ([['air', 'Lọc bụi mịn', 'PM2.5'], ['leaf', 'Khử mùi', 'hiệu quả'], ['shield', 'Lọc sạch', 'đến 99,97%'], ['heart', 'Không khí', 'trong lành']] as [$icon, $line1, $line2])<div><span><x-landing.purehome-icon :name="$icon" /></span><b>{{ $line1 }}<br>{{ $line2 }}</b></div>@endforeach</div><a class="fa-hero-cta" href="#san-pham">Khám phá FreshAir S8 <x-landing.purehome-icon name="arrow" /></a></div>
                    <p class="fa-hero-note">Sạch từng hơi thở<br>Yêu thương dài lâu ♡</p>
                </div>
                <aside class="fa-hero-benefits" aria-label="Ưu điểm FreshAir S8">
                    @foreach ([['leaf', 'Lọc PM2.5 hiệu quả', 'Đến 99,97% bụi mịn'], ['shield', 'Khử mùi & VOCs', 'Mùi hôi, khói, hóa chất'], ['quiet', 'Vận hành êm ái', 'Độ ồn chỉ từ 22 dB'], ['bolt', 'Tiết kiệm điện', 'Công suất chỉ 28W'], ['home', 'Phù hợp mọi không gian', 'Phòng ngủ, phòng khách, văn phòng'], ['shield', 'Bảo hành 24 tháng', 'Yên tâm sử dụng']] as [$icon, $title, $text])<div><span><x-landing.purehome-icon :name="$icon" /></span><p><strong>{{ $title }}</strong><small>{{ $text }}</small></p></div>@endforeach
                </aside>
            </div>
        </section>

        <section class="fa-container fa-shop" id="san-pham" aria-labelledby="fa-product-title" data-search-section="sản phẩm máy lọc freshair giá mua hàng">
            <div class="fa-product-gallery">
                <div class="swiper fa-thumbnails" aria-label="Chọn ảnh sản phẩm">
                    <div class="swiper-wrapper">
                        @foreach ($productGallery as [$scene, $title])
                            <div class="swiper-slide"><button data-photo-index="{{ $loop->index }}" type="button" aria-label="{{ $title }}" aria-pressed="{{ $loop->first ? 'true' : 'false' }}">
                                @if ($scene === 'product')<img src="{{ asset('landing/freshair/product.webp') }}" alt="" width="100" height="100">@else<span class="fa-scene fa-scene-{{ $scene }}"></span>@endif
                            </button></div>
                        @endforeach
                    </div>
                </div>
                <div class="swiper fa-product-slider" aria-label="Ảnh sản phẩm FreshAir S8">
                    <div class="swiper-wrapper">
                        @foreach ($productGallery as [$scene, $title])
                            <div class="swiper-slide"><button class="fa-main-photo" type="button" data-gallery-open="{{ $scene === 'product' ? 'product' : $loop->index - 1 }}" aria-label="Phóng to: {{ $title }}">
                                @if ($scene === 'product')<img src="{{ asset('landing/freshair/product.webp') }}" alt="{{ $title }}" width="1254" height="1254">@else<span class="fa-main-sprite fa-scene fa-scene-{{ $scene }}" role="img" aria-label="{{ $title }}"></span>@endif
                                <span class="fa-photo-zoom">＋ Xem ảnh lớn</span>
                            </button></div>
                        @endforeach
                    </div>
                    <button class="fa-slider-arrow fa-product-prev" type="button" aria-label="Ảnh sản phẩm trước">‹</button>
                    <button class="fa-slider-arrow fa-product-next" type="button" aria-label="Ảnh sản phẩm tiếp theo">›</button>
                </div>
                <div class="fa-slider-footer"><span>Kéo để xem thêm ảnh</span><span class="fa-product-pagination"></span></div>
            </div>
            <div class="fa-product-info"><div class="fa-product-badges"><span>Bán chạy</span><span>✧ Thương hiệu được tin chọn</span></div><h2 id="fa-product-title">Máy lọc không khí FreshAir S8</h2><p class="fa-product-tagline">Không khí sạch hơn · Cuộc sống khỏe mạnh hơn</p><div class="fa-rating"><span class="fa-stars" aria-label="4,9 trên 5 sao">★★★★★</span><strong>4.9/5</strong><span>|</span><a href="#danh-gia">2.4k đánh giá</a><span>|</span><span>Đã bán <b>8.7k</b></span></div><div class="fa-price-box"><div><x-landing.purehome-icon name="bolt" /><strong>GIÁ SIÊU SALE HÔM NAY</strong><span>Ưu đãi độc quyền</span></div><div class="fa-price-content"><div><del>5.990.000đ</del><strong class="fa-price">3.590.000đ</strong></div><b class="fa-discount">Giảm 40%</b><span class="fa-price-note">Giá tốt cho<br>cuộc sống xanh</span></div></div><h3 class="fa-small-heading">Voucher ưu đãi</h3><div class="fa-vouchers"><button type="button" data-voucher="FRESH300"><x-landing.purehome-icon name="gift" /><span><strong>Giảm 300K</strong><small>Đơn từ 3.5 triệu</small></span></button><button type="button" data-voucher="FRESH10"><x-landing.purehome-icon name="gift" /><span><strong>Giảm 10%</strong><small>Tối đa 200K</small></span></button><button type="button" data-voucher="FREESHIP"><x-landing.purehome-icon name="truck" /><span><strong>FREESHIP</strong><small>Toàn quốc</small></span></button></div><p class="fa-voucher-help">Chạm để lấy mã · Áp dụng theo điều kiện từng ưu đãi</p><h3 class="fa-small-heading">Hình thức thanh toán</h3><div class="fa-payment-options"><span><x-landing.purehome-icon name="shield" /><span><b>Thanh toán an toàn</b><small>Xác nhận trực tiếp khi đặt mua</small></span></span><span><x-landing.purehome-icon name="truck" /><span><b>Thanh toán khi nhận hàng</b><small>(COD)</small></span></span></div><div class="fa-quantity-line"><label for="fa-quantity">Số lượng:</label><div class="fa-quantity"><button type="button" data-quantity-step="-1" aria-label="Giảm số lượng">−</button><input id="fa-quantity" type="number" value="1" min="1" max="10" inputmode="numeric" aria-label="Số lượng sản phẩm"><button type="button" data-quantity-step="1" aria-label="Tăng số lượng">+</button></div><span class="fa-stock">● Sẵn hàng · Giao ngay</span></div></div>
            <div class="fa-buy-panel"><button class="fa-button fa-button-red" type="button" data-buy><x-landing.purehome-icon name="cart" /><span><strong>MUA NGAY</strong><small>Giao nhanh tận nhà</small></span></button><button class="fa-button fa-button-outline" type="button" data-add-cart><x-landing.purehome-icon name="cart" /><span><strong>Thêm vào giỏ</strong><small>Tiện lợi, mua thêm sản phẩm khác</small></span></button><div class="fa-buy-perks"><span><x-landing.purehome-icon name="truck" /><span><b>Giao nhanh toàn quốc</b><small>Nhận hàng 1 - 3 ngày</small></span></span><span><x-landing.purehome-icon name="rotate" /><span><b>Đổi trả 7 ngày</b><small>Nếu có lỗi từ nhà sản xuất</small></span></span><span><x-landing.purehome-icon name="shield" /><span><b>Hàng chính hãng 100%</b><small>Có đầy đủ hóa đơn, bảo hành</small></span></span></div><a class="fa-consult-link" href="#tu-van"><x-landing.purehome-icon name="phone" />Cần tư vấn? Để FreshAir giúp bạn</a><button class="fa-share-button" type="button" data-share><x-landing.purehome-icon name="arrow" />Chia sẻ sản phẩm</button></div>
        </section>

        <div class="fa-container fa-trust-strip">@foreach ([['truck', 'Giao nhanh toàn quốc', 'Nhận hàng 1 - 3 ngày'], ['shield', 'Hàng chính hãng 100%', 'Có đầy đủ hóa đơn, bảo hành'], ['rotate', 'Đổi trả 7 ngày', 'Nếu có lỗi từ nhà sản xuất'], ['gift', 'Thanh toán khi nhận hàng', 'An toàn · Tiện lợi']] as [$icon, $title, $text])<div><x-landing.purehome-icon :name="$icon" /><span><strong>{{ $title }}</strong><small>{{ $text }}</small></span></div>@endforeach<div class="fa-family-trust"><x-landing.purehome-icon name="family" /><span>Hơn <b>8.7K ♥</b><small>GIA ĐÌNH ĐÃ TIN DÙNG FRESHAIR S8</small></span></div></div>

        <section class="fa-container fa-section" id="hinh-anh" aria-labelledby="fa-gallery-title" data-search-section="hình ảnh thực tế bộ sưu tập phòng ngủ phòng khách văn phòng gia đình">
            <div class="fa-section-heading"><span class="fa-heading-icon fa-coral"><svg viewBox="0 0 32 32" fill="currentColor" aria-hidden="true"><path d="M5 9h5l2-4h8l2 4h5a3 3 0 0 1 3 3v14a3 3 0 0 1-3 3H5a3 3 0 0 1-3-3V12a3 3 0 0 1 3-3Z"/><circle cx="16" cy="18" r="6" fill="none" stroke="white" stroke-width="2"/></svg></span><div><h2 id="fa-gallery-title">Bộ ảnh sưu tầm / Hình ảnh thực tế</h2><p>Khám phá máy lọc không khí FreshAir S8 trong không gian sống</p></div><button type="button" class="fa-text-button" data-gallery-open="0">Xem tất cả hình ảnh <span>→</span></button></div>
            <div class="swiper fa-gallery-grid" aria-label="Hình ảnh FreshAir trong không gian sống"><div class="swiper-wrapper">@foreach ($gallery as [$scene, $title, $caption])<button class="swiper-slide fa-gallery-card" type="button" data-gallery-open="{{ $loop->index }}"><span class="fa-scene fa-scene-{{ $scene }}" role="img" aria-label="{{ $title }}"></span><span class="fa-gallery-caption"><strong>{{ $title }}</strong><small>{{ $caption }}</small></span></button>@endforeach</div><div class="fa-gallery-pagination"></div></div>
        </section>

        <section class="fa-container fa-technology-grid" id="cong-nghe" aria-label="Công nghệ, thông số và tư vấn" data-search-section="công nghệ thông số diện tích cadr hepa màng lọc công suất điện ồn kích thước trọng lượng">
            <article class="fa-filter-card"><div class="fa-section-heading"><span class="fa-heading-icon"><x-landing.purehome-icon name="air" /></span><div><h2>Công nghệ lọc tiên tiến</h2><p>Bảo vệ toàn diện cho gia đình bạn</p></div></div><img src="{{ asset('landing/purehome/filters.webp') }}" alt="Cấu tạo hệ thống màng lọc bốn lớp FreshAir S8" width="1254" height="1254" loading="lazy"><ol>@foreach ([['Màng lọc thô', 'Giữ bụi lớn, lông thú'], ['Màng lọc HEPA H13', 'Lọc 99,97% bụi mịn PM2.5, vi khuẩn, phấn hoa'], ['Than hoạt tính', 'Khử mùi, VOCs, khí độc'], ['Màng lọc bổ trợ', 'Không khí sạch hơn, trong lành hơn']] as [$title, $text])<li><b>{{ $loop->iteration }}</b><span><strong>{{ $title }}</strong><small>{{ $text }}</small></span></li>@endforeach</ol></article>
            <article class="fa-specs-card"><div class="fa-section-heading"><span class="fa-heading-icon"><x-landing.purehome-icon name="touch" /></span><h2>Thông số kỹ thuật</h2></div><dl>@foreach ([['Model', 'FreshAir S8'], ['Diện tích sử dụng', '20 - 50 m²'], ['CADR (Lưu lượng khí sạch)', '320 m³/h'], ['Màng lọc', 'HEPA H13 + Than hoạt tính + Màng lọc thô'], ['Độ ồn', '22 - 50 dB'], ['Công suất', '28W'], ['Kích thước', '250 × 250 × 520 mm'], ['Trọng lượng', '4.8 kg'], ['Màu sắc', 'Trắng'], ['Bảo hành', '24 tháng']] as [$label, $value])<div><dt>{{ $label }}</dt><dd>{{ $value }}</dd></div>@endforeach</dl><p class="fa-spec-note"><x-landing.purehome-icon name="shield" />Chọn đúng công suất cho không gian của bạn</p></article>
            <section class="fa-consult-card" id="tu-van" aria-labelledby="fa-consult-title"><div class="fa-section-heading"><span class="fa-heading-icon"><x-landing.purehome-icon name="leaf" /></span><div><h2 id="fa-consult-title">Đăng ký tư vấn miễn phí</h2><p>Để lại thông tin, chuyên gia của chúng tôi sẽ giúp bạn chọn sản phẩm phù hợp.</p></div></div><form id="fa-consult-form"><label><span>Họ và tên <b>*</b></span><input type="text" name="name" placeholder="Họ và tên của bạn" required maxlength="80" autocomplete="name"></label><label><span>Số điện thoại <b>*</b></span><input type="tel" name="phone" placeholder="Số điện thoại liên hệ" required pattern="\+?[0-9][0-9 \-]{7,18}[0-9]" maxlength="20" autocomplete="tel" inputmode="tel"></label><label><span>Email <small>(không bắt buộc)</small></span><input type="email" name="email" placeholder="Địa chỉ email" maxlength="120" autocomplete="email"></label><label><span>Nhu cầu sử dụng</span><select name="room"><option>Phòng khách</option><option>Phòng ngủ</option><option>Văn phòng</option><option>Cần tư vấn thêm</option></select></label><button class="fa-button fa-button-red" type="submit"><span><strong>ĐĂNG KÝ TƯ VẤN NGAY</strong><small>Nhận ưu đãi đặc biệt hôm nay</small></span></button><p class="fa-form-note"><x-landing.purehome-icon name="shield" />Xác nhận yêu cầu qua email hoặc hotline</p></form></section>
        </section>

        <section class="fa-container fa-section" id="uu-dai" aria-labelledby="fa-gifts-title" data-search-section="ưu đãi khuyến mãi voucher quà tặng combo giảm giá freeship">
            <div class="fa-section-heading"><span class="fa-heading-icon fa-coral"><x-landing.purehome-icon name="gift" /></span><div><h2 id="fa-gifts-title">Combo ưu đãi / Quà tặng kèm</h2><p>Mua máy lọc không khí FreshAir S8 ngay hôm nay để nhận những phần quà giá trị</p></div></div><div class="fa-gift-grid"><article class="fa-gift-card"><span class="fa-gift-photo fa-gift-filter" role="img" aria-label="Bộ lọc HEPA H13 tặng kèm"></span><div><b class="fa-gift-label">TẶNG NGAY</b><h3>Bộ lọc HEPA <em>H13</em></h3><p>Trị giá <strong>890.000đ</strong></p><small>Thay trong 6 - 12 tháng</small></div></article><article class="fa-gift-card"><span class="fa-gift-photo fa-gift-meter" role="img" aria-label="Nhiệt ẩm kế thông minh"></span><div><b class="fa-gift-label">TẶNG NGAY</b><h3>Nhiệt ẩm kế thông minh</h3><p>Trị giá <strong>350.000đ</strong></p><small>Theo dõi chất lượng không khí</small></div></article><button type="button" class="fa-gift-card fa-gift-voucher" data-voucher="FRESH10"><span class="fa-ticket">%</span><span><b class="fa-gift-label">VOUCHER</b><strong>Giảm thêm <em>10%</em></strong><small>Cho lần mua tiếp theo</small></span></button><article class="fa-gift-message"><x-landing.purehome-icon name="gift" /><div><h3>QUÀ TẶNG GIÁ TRỊ!</h3><p>Đồng hành cùng<br>bầu không khí sạch!</p></div></article></div>
        </section>

        <section class="fa-container fa-section fa-why" aria-labelledby="fa-why-title"><div class="fa-section-heading"><span class="fa-heading-icon"><x-landing.purehome-icon name="diamond" /></span><h2 id="fa-why-title">Vì sao nên chọn FreshAir?</h2></div><div class="fa-why-grid">@foreach ([['air', 'Lọc sạch 99,97%', 'Bụi mịn PM2.5'], ['leaf', 'Khử mùi vượt trội', 'Mùi hôi, VOCs, khói thuốc'], ['heart', 'Bảo vệ sức khỏe', 'Cho cả gia đình'], ['bolt', 'Tiết kiệm điện', 'Công suất chỉ 28W'], ['quiet', 'Vận hành êm ái', 'Ngủ ngon, sống khỏe'], ['shield', 'Thương hiệu uy tín', 'Hàng chính hãng 100%']] as [$icon, $title, $text])<article><span><x-landing.purehome-icon :name="$icon" /></span><div><h3>{{ $title }}</h3><p>{{ $text }}</p></div></article>@endforeach</div></section>

        <section class="fa-container fa-section" id="danh-gia" aria-labelledby="fa-reviews-title" data-search-section="đánh giá khách hàng nhận xét tin dùng">
            <div class="fa-section-heading"><span class="fa-heading-icon fa-gold">★</span><div><h2 id="fa-reviews-title">Đánh giá khách hàng</h2><p>Hơn 2.4k khách hàng đã đánh giá với điểm trung bình <b class="fa-orange">4.9/5</b></p></div><button type="button" class="fa-text-button" data-open-reviews>Xem tất cả đánh giá <span>→</span></button></div><div class="fa-reviews-grid" id="fa-reviews-list">@foreach ([['lan', 'Nguyễn Thị Mai', 'Máy chạy rất êm, lọc không khí tốt. Phòng ngủ thoáng hơn hẳn, bé nhà mình cũng ít ho hơn.', ['living', 'bedroom', 'family']], ['hoang', 'Trần Văn Hùng', 'Thiết kế đẹp, dễ sử dụng. Màn hình hiển thị rất trực quan. Giao hàng nhanh, đóng gói cẩn thận.', ['display', 'filter', 'living']], ['huong', 'Lê Thu Hà', 'Không khí trong lành hơn rõ rệt, mùi thức ăn cũng được khử nhanh. Rất đáng mua!', ['living', 'office', 'family']], ['hoang', 'Phạm Quang Minh', 'Sản phẩm chất lượng, gia đình mình rất hài lòng. Sẽ giới thiệu cho bạn bè.', ['office', 'living', 'bedroom']]] as [$avatar, $name, $review, $photos])<article class="fa-review-card"><header><span class="fa-avatar fa-avatar-{{ $avatar }}" role="img" aria-label="Ảnh minh họa khách hàng"></span><div><h3>{{ $name }}</h3><div><span class="fa-stars" aria-label="5 trên 5 sao">★★★★★</span><small>✓ Đã mua hàng</small></div></div></header><p>{{ $review }}</p><div class="fa-review-photos">@foreach ($photos as $scene)<button type="button" data-gallery-open="{{ array_search($scene, array_column($gallery, 0)) }}" aria-label="Xem ảnh {{ $scene === 'living' ? 'phòng khách' : 'trải nghiệm sản phẩm' }}"><span class="fa-scene fa-scene-{{ $scene }}"></span></button>@endforeach</div></article>@endforeach</div>
        </section>

        <section class="fa-container fa-section fa-faq" id="hoi-dap" aria-labelledby="fa-faq-title" data-search-section="câu hỏi hỏi đáp bảo hành điện diện tích màng lọc đổi trả giao hàng"><div class="fa-section-heading"><span class="fa-heading-icon fa-question">?</span><div><h2 id="fa-faq-title">Câu hỏi thường gặp (FAQ)</h2><p>Giải đáp những thắc mắc phổ biến về máy lọc không khí FreshAir S8</p></div></div><div class="fa-faq-grid">@foreach ([['Máy lọc không khí FreshAir S8 phù hợp với diện tích bao nhiêu?', 'FreshAir S8 phù hợp cho không gian 20 - 50 m². Đặt máy ở vị trí thông thoáng và tránh che kín cửa hút, thoát khí để máy hoạt động hiệu quả.'], ['Chính sách bảo hành như thế nào?', 'FreshAir S8 được bảo hành chính hãng 24 tháng. Giữ hóa đơn hoặc thông tin đặt hàng và liên hệ hotline 1900 636 888 khi cần hỗ trợ.'], ['Màng lọc HEPA H13 có thể sử dụng trong bao lâu?', 'Thời gian thay màng lọc tham khảo là 6 - 12 tháng, tùy chất lượng không khí và tần suất sử dụng. Kiểm tra màng lọc định kỳ theo hướng dẫn sử dụng.'], ['Tôi có thể đổi trả hàng không?', 'Bạn được hỗ trợ đổi trả trong 7 ngày nếu sản phẩm có lỗi từ nhà sản xuất. Liên hệ FreshAir trước khi gửi lại sản phẩm để được hướng dẫn.'], ['Máy có tốn nhiều điện không?', 'Máy có công suất 28W, phù hợp sử dụng hàng ngày. Điện năng tiêu thụ thực tế phụ thuộc chế độ và thời gian hoạt động.'], ['Thời gian giao hàng mất bao lâu?', 'Thời gian giao hàng dự kiến 1 - 3 ngày tùy khu vực. FreshAir xác nhận thời gian cụ thể cùng bạn khi chốt đơn hàng.']] as [$question, $answer])<details><summary>{{ $question }}<span aria-hidden="true">⌄</span></summary><p>{{ $answer }}</p></details>@endforeach</div></section>
    </main>
    <footer class="fa-footer"><div class="fa-container"><a class="fa-brand" href="#trang-chu"><x-landing.purehome-icon name="leaf" /><span><strong>FreshAir Mall</strong><small>Không khí sạch. Cuộc sống xanh</small></span></a><p>Đồng hành cùng bầu không khí sạch<br>cho mọi gia đình Việt.</p><a href="tel:1900636888"><x-landing.purehome-icon name="phone" />1900 636 888</a><a href="mailto:cskh@freshair.vn">cskh@freshair.vn</a><button type="button" data-share>Chia sẻ sản phẩm ↗</button></div></footer>
    <aside class="fa-sticky-buy" aria-label="Đặt mua nhanh"><div class="fa-container"><img src="{{ asset('landing/freshair/product.webp') }}" width="64" height="64" alt="FreshAir S8"><div class="fa-sticky-product"><strong>Máy lọc không khí FreshAir S8</strong><div><del>5.990.000đ</del><b>3.590.000đ</b><span class="fa-discount">Giảm 40%</span></div></div><div class="fa-sticky-perks"><span><x-landing.purehome-icon name="truck" />Freeship<br>toàn quốc</span><span><x-landing.purehome-icon name="shield" />Bảo hành<br>24 tháng</span><span><x-landing.purehome-icon name="rotate" />Đổi trả<br>7 ngày</span></div><button class="fa-button fa-button-red" type="button" data-buy><x-landing.purehome-icon name="cart" /><span><strong>MUA NGAY</strong><small>Giao nhanh tận nhà</small></span></button></div></aside>

    <div class="fa-toast" role="status" aria-live="polite" hidden></div>
    <dialog class="fa-dialog" id="fa-cart-dialog" aria-labelledby="fa-cart-title"><button class="fa-dialog-close fa-icon-button" type="button" data-close-dialog aria-label="Đóng"><x-landing.purehome-icon name="close" /></button><h2 id="fa-cart-title">Giỏ hàng của bạn</h2><div class="fa-cart-empty"><x-landing.purehome-icon name="cart" /><p>Giỏ hàng đang trống.</p><button class="fa-button fa-button-green" type="button" data-close-dialog>Tiếp tục xem sản phẩm</button></div><div class="fa-cart-content" hidden><div class="fa-cart-product"><img src="{{ asset('landing/freshair/product.webp') }}" alt="FreshAir S8" width="120" height="120"><div><h3>Máy lọc không khí FreshAir S8</h3><p>Màu trắng · Số lượng: <b data-cart-quantity>1</b></p><strong class="fa-price">3.590.000đ</strong></div></div><div class="fa-cart-total"><span>Tạm tính</span><strong data-cart-total>3.590.000đ</strong></div><p class="fa-dialog-description">Miễn phí giao hàng toàn quốc. Liên hệ FreshAir để xác nhận ưu đãi, địa chỉ và thời gian nhận hàng.</p><a class="fa-button fa-button-red" href="tel:1900636888"><x-landing.purehome-icon name="phone" />Gọi đặt hàng: 1900 636 888</a><a class="fa-email-order" href="mailto:cskh@freshair.vn" data-order-email>Gửi yêu cầu đặt hàng qua email</a><button class="fa-remove-cart" type="button" data-clear-cart>Xóa sản phẩm khỏi giỏ</button></div></dialog>
    <dialog class="fa-dialog fa-lightbox" id="fa-gallery-dialog" aria-labelledby="fa-gallery-caption">
        <button class="fa-dialog-close fa-icon-button" type="button" data-close-dialog aria-label="Đóng ảnh"><x-landing.purehome-icon name="close" /></button>
        <div class="swiper fa-lightbox-slider" aria-label="Xem ảnh phóng to">
            <div class="swiper-wrapper">
                @foreach ($productGallery as [$scene, $title])
                    <div class="swiper-slide" data-caption="{{ $title }}">
                        @if ($scene === 'product')<img class="fa-lightbox-image" src="{{ asset('landing/freshair/product.webp') }}" alt="{{ $title }}" width="1254" height="1254" loading="lazy">@else<div class="fa-lightbox-image fa-scene fa-scene-{{ $scene }}" role="img" aria-label="{{ $title }}"></div>@endif
                    </div>
                @endforeach
            </div>
        </div>
        <div class="fa-lightbox-controls"><button class="fa-lightbox-prev" type="button" aria-label="Ảnh trước">←</button><p id="fa-gallery-caption" aria-live="polite">Máy lọc không khí FreshAir S8 · 1/7</p><button class="fa-lightbox-next" type="button" aria-label="Ảnh tiếp theo">→</button></div>
    </dialog>
    <dialog class="fa-dialog fa-reviews-dialog" id="fa-reviews-dialog" aria-labelledby="fa-all-reviews-title"><button class="fa-dialog-close fa-icon-button" type="button" data-close-dialog aria-label="Đóng đánh giá"><x-landing.purehome-icon name="close" /></button><h2 id="fa-all-reviews-title">Khách hàng nói về FreshAir S8</h2><p class="fa-dialog-description"><span class="fa-stars">★★★★★</span> Những trải nghiệm được chia sẻ</p><div class="fa-reviews-dialog-list"></div></dialog>
    <dialog class="fa-dialog" id="fa-consult-dialog" aria-labelledby="fa-consult-dialog-title"><button class="fa-dialog-close fa-icon-button" type="button" data-close-dialog aria-label="Đóng tư vấn"><x-landing.purehome-icon name="close" /></button><h2 id="fa-consult-dialog-title">Thông tin tư vấn của bạn</h2><p class="fa-dialog-description">Kiểm tra thông tin bên dưới, rồi chọn gửi yêu cầu qua email hoặc gọi hotline FreshAir.</p><dl class="fa-consult-summary"></dl><a class="fa-button fa-button-red" data-consult-email href="mailto:cskh@freshair.vn"><x-landing.purehome-icon name="mail" />Gửi yêu cầu qua email</a><a class="fa-email-order" href="tel:1900636888">Gọi tư vấn: 1900 636 888</a></dialog>
    <dialog class="fa-dialog" id="fa-share-dialog" aria-labelledby="fa-share-title"><button class="fa-dialog-close fa-icon-button" type="button" data-close-dialog aria-label="Đóng chia sẻ"><x-landing.purehome-icon name="close" /></button><h2 id="fa-share-title">Chia sẻ không khí trong lành</h2><img class="fa-share-preview" src="{{ asset('landing/freshair/share.jpg') }}" alt="Ảnh chia sẻ FreshAir S8" width="1200" height="630" loading="lazy"><p class="fa-dialog-description">Gửi FreshAir S8 tới người thân và bạn bè.</p><label class="fa-share-url"><span>Đường dẫn sản phẩm</span><input readonly value="{{ route('landing.freshair') }}" aria-label="Đường dẫn chia sẻ sản phẩm"></label><button class="fa-button fa-button-green" type="button" data-copy-share>Sao chép đường dẫn</button><button class="fa-native-share" type="button" data-native-share hidden>Chia sẻ bằng ứng dụng trên thiết bị</button></dialog>
    <script src="{{ asset('vendor/swiper/swiper-bundle.min.js') }}"></script>
</body>
</html>
