@extends('layouts.tool')

@section('tool-content')
<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-lg-10">
            <!-- Header -->
            <div class="text-center mb-5">
                <h1 class="display-4 fw-bold text-primary mb-2">Lịch Vạn Niên</h1>
                <p class="lead text-muted">Xem lịch âm dương, ngày tốt xấu chuẩn xác.</p>
            </div>

            <!-- Today Card -->
            <div class="card shadow-lg border-0 mb-5 overflow-hidden">
                <div class="row g-0">
                    <!-- Left: Solar Date -->
                    <div class="col-md-6 tool-result rounded-0 p-5 d-flex flex-column justify-content-center align-items-center position-relative">
                        <div class="position-absolute" style="top: 20px; left: 20px; opacity: 0.5; font-size: 5rem;">
                            <x-icon name="sun" />
                        </div>
                        <h5 class="text-uppercase letter-spacing-2 mb-3">Dương Lịch</h5>
                        <h1 class="display-1 fw-bold mb-0" id="todayDay">--</h1>
                        <h3 class="fw-light mb-0" id="todayMonthYear">--/----</h3>
                        <p class="mt-3 mb-0 text-white-50" id="todayWeekday">Thứ --</p>
                    </div>
                    
                    <!-- Right: Lunar Date -->
                    <div class="col-md-6 bg-white p-5 d-flex flex-column justify-content-center align-items-center position-relative">
                        <div class="position-absolute" style="top: 20px; right: 20px; opacity: 0.1; font-size: 5rem; color: #000;">
                            <x-icon name="moon" />
                        </div>
                        <h5 class="text-uppercase letter-spacing-2 mb-3 text-secondary">Âm Lịch</h5>
                        <h1 class="display-1 fw-bold text-dark mb-0" id="lunarDay">--</h1>
                        <h3 class="fw-light text-muted mb-0" id="lunarMonthYear">--/----</h3>
                        <p class="mt-3 mb-0 text-danger fw-bold" id="canChi">-- --</p>
                    </div>
                </div>
            </div>

            <!-- Calendar Grid -->
            <div class="card shadow-sm border-0">
                <div class="card-header bg-white border-bottom-0 pt-4 pb-0 d-flex justify-content-between align-items-center">
                    <h3 class="h5 mb-0 fw-bold" id="calHeader">Tháng -- Năm ----</h3>
                    <div class="btn-group">
                        <button class="btn btn-outline-primary btn-sm" onclick="prevMonth()"><x-icon name="chevron-left" /></button>
                        <button class="btn btn-outline-primary btn-sm" onclick="goToday()">Hôm nay</button>
                        <button class="btn btn-outline-primary btn-sm" onclick="nextMonth()"><x-icon name="chevron-right" /></button>
                    </div>
                </div>
                <div class="card-body p-4">
                    <div class="calendar-grid">
                        <div class="row text-center mb-3 fw-bold text-muted text-uppercase small">
                            <div class="col">CN</div>
                            <div class="col">T2</div>
                            <div class="col">T3</div>
                            <div class="col">T4</div>
                            <div class="col">T5</div>
                            <div class="col">T6</div>
                            <div class="col">T7</div>
                        </div>
                        <div id="calendarDays" class="calendar-days">
                            <!-- Days generated by JS -->
                        </div>
                    </div>
                </div>
                <div class="card-footer bg-white border-top-0 pb-4 text-center">
                    <small class="text-muted"><x-icon name="info" class="me-1" /> Số nhỏ bên dưới là ngày Âm lịch</small>
                </div>
            </div>
            
        </div>
    </div>
</div>

<style>
    .letter-spacing-2 { letter-spacing: 2px; }
    .calendar-days { display: grid; grid-template-columns: repeat(7, 1fr); gap: 10px; }
    .cal-day { 
        min-height: 80px; 
        border-radius: 12px; 
        background-color: #f8f9fa; 
        display: flex; 
        flex-direction: column; 
        justify-content: center; 
        align-items: center; 
        cursor: pointer; 
        transition: all 0.2s;
        border: 1px solid transparent;
    }
    .cal-day:hover { background-color: #e9ecef; transform: translateY(-2px); box-shadow: 0 4px 6px rgba(0,0,0,0.05); }
    .cal-day.today { background-color: #e3f2fd; border-color: #2196f3; color: #2196f3; }
    .cal-day.today .lunar { color: #1976d2; }
    .cal-day.empty { background: transparent; cursor: default; }
    .cal-day .solar { font-size: 1.5rem; font-weight: bold; line-height: 1; }
    .cal-day .lunar { font-size: 0.85rem; color: #6c757d; margin-top: 5px; }
    .cal-day.sunday .solar { color: #dc3545; }
</style>

@push('scripts')
<!-- Lunar Calendar Library from CDN -->
<!-- Lunar Calendar Library -->
<script src="/vendor/lunar-1.7.7.js"></script>

<script>
    // Init dates
    let currentMonth = new Date().getMonth();
    let currentYear = new Date().getFullYear();
    const today = new Date();

    const weekDays = ['Chủ Nhật', 'Thứ Hai', 'Thứ Ba', 'Thứ Tư', 'Thứ Năm', 'Thứ Sáu', 'Thứ Bảy'];
    const can = ['Canh', 'Tân', 'Nhâm', 'Quý', 'Giáp', 'Ất', 'Bính', 'Đinh', 'Mậu', 'Kỷ'];
    const chi = ['Thân', 'Dậu', 'Tuất', 'Hợi', 'Tý', 'Sửu', 'Dần', 'Mão', 'Thìn', 'Tỵ', 'Ngọ', 'Mùi'];

    const text = (id, value) => { document.getElementById(id).textContent = value; };

    // lunar-javascript: Solar.fromDate(date).getLunar() gives the lunar day, month and year.
    function lunarOf(date) {
        const lunar = Solar.fromDate(date).getLunar();
        return { day: lunar.getDay(), month: Math.abs(lunar.getMonth()), leap: lunar.getMonth() < 0, year: lunar.getYear() };
    }

    function canChi(lunarYear) {
        return `${can[lunarYear % 10]} ${chi[lunarYear % 12]}`;
    }

    function renderToday() {
        text('todayDay', today.getDate());
        text('todayMonthYear', `Tháng ${today.getMonth() + 1}/${today.getFullYear()}`);
        text('todayWeekday', weekDays[today.getDay()]);

        const lunar = lunarOf(today);
        text('lunarDay', lunar.day);
        text('lunarMonthYear', `Tháng ${lunar.month}${lunar.leap ? ' (nhuận)' : ''} Năm ${lunar.year}`);
        text('canChi', `Năm ${canChi(lunar.year)}`);
    }

    function renderCalendar(month, year) {
        text('calHeader', `Tháng ${month + 1} Năm ${year}`);

        const startDayIndex = new Date(year, month, 1).getDay();
        const daysInMonth = new Date(year, month + 1, 0).getDate();
        const grid = document.getElementById('calendarDays');
        const cells = [];

        for (let i = 0; i < startDayIndex; i++) {
            cells.push('<div class="cal-day empty"></div>');
        }

        for (let d = 1; d <= daysInMonth; d++) {
            const date = new Date(year, month, d);
            const lunar = lunarOf(date);
            const classes = ['cal-day'];
            if (date.toDateString() === today.toDateString()) classes.push('today');
            if (date.getDay() === 0) classes.push('sunday');
            const lunarLabel = lunar.day === 1 ? `${lunar.day}/${lunar.month}` : lunar.day;
            cells.push(`<div class="${classes.join(' ')}"><div class="solar">${d}</div><div class="lunar">${lunarLabel}</div></div>`);
        }

        grid.innerHTML = cells.join('');
    }

    document.addEventListener('DOMContentLoaded', function () {
        renderToday();
        renderCalendar(currentMonth, currentYear);
    });

    function prevMonth() {
        currentMonth--;
        if(currentMonth < 0) {
            currentMonth = 11;
            currentYear--;
        }
        renderCalendar(currentMonth, currentYear);
    }

    function nextMonth() {
        currentMonth++;
        if(currentMonth > 11) {
            currentMonth = 0;
            currentYear++;
        }
        renderCalendar(currentMonth, currentYear);
    }
    
    function goToday() {
        currentMonth = new Date().getMonth();
        currentYear = new Date().getFullYear();
        renderCalendar(currentMonth, currentYear);
    }
</script>
@endpush
@endsection
