<?php

declare(strict_types=1);

return [
    'business' => [
        'route' => 'website-doanh-nghiep.php',
        'slug' => 'website-doanh-nghiep',
        'menu_key' => 'business',
        'eyebrow' => 'WEBSITE DOANH NGHIỆP',
        'title' => 'Website doanh nghiệp chuyên nghiệp để khách hàng tin và liên hệ',
        'highlight' => 'Nền tảng giới thiệu năng lực, sản phẩm và dự án rõ ràng.',
        'description' => 'Dành cho công ty sản xuất, thương mại và dịch vụ cần một website đủ tin cậy để gửi khách hàng, đối tác, đại lý và ứng viên.',
        'meta_title' => 'Thiết kế website doanh nghiệp tại Bắc Ninh | WebApp Bắc Ninh',
        'meta_description' => 'Thiết kế website doanh nghiệp tại Bắc Ninh: giới thiệu năng lực, sản phẩm, dịch vụ, dự án, tuyển dụng và form nhận khách hàng. Dễ quản trị, SEO nền tảng.',
        'image' => 'assets/images/project-corporate.webp',
        'secondary_image' => 'assets/images/about-bacninh.webp',
        'icon' => 'fa-solid fa-building',
        'price_from' => 'Từ 8 triệu',
        'timeline' => '2 - 4 tuần',
        'cta' => 'Nhận cấu trúc website doanh nghiệp',
        'need_value' => 'Thiết kế website doanh nghiệp',
        'audiences' => [
            'Doanh nghiệp sản xuất và nhà máy trong khu công nghiệp',
            'Công ty thương mại, phân phối và xuất nhập khẩu',
            'Doanh nghiệp dịch vụ cần hồ sơ năng lực trực tuyến',
            'Công ty đang dùng website cũ, thiếu chuyên nghiệp hoặc khó cập nhật',
        ],
        'problems' => [
            ['icon' => 'fa-solid fa-file-circle-question', 'title' => 'Nội dung rời rạc', 'text' => 'Khách hàng không thấy rõ năng lực, sản phẩm chủ lực và lý do nên lựa chọn doanh nghiệp.'],
            ['icon' => 'fa-solid fa-mobile-screen', 'title' => 'Hiển thị mobile kém', 'text' => 'Website cũ khó đọc trên điện thoại, nút liên hệ nhỏ và tốc độ tải chậm.'],
            ['icon' => 'fa-solid fa-user-slash', 'title' => 'Không tạo được lead', 'text' => 'Có lượt truy cập nhưng thiếu form, CTA, hotline và luồng chuyển đổi rõ ràng.'],
        ],
        'pages' => ['Trang chủ', 'Giới thiệu', 'Sản phẩm / Dịch vụ', 'Năng lực / Dự án', 'Tin tức', 'Tuyển dụng', 'Liên hệ'],
        'features' => [
            ['icon' => 'fa-solid fa-palette', 'title' => 'Theo nhận diện thương hiệu', 'text' => 'Màu sắc, font, hình ảnh và bố cục phù hợp doanh nghiệp.'],
            ['icon' => 'fa-solid fa-layer-group', 'title' => 'Cấu trúc rõ ràng', 'text' => 'Sắp xếp nội dung theo cách khách hàng dễ hiểu và dễ tìm.'],
            ['icon' => 'fa-solid fa-language', 'title' => 'Có thể đa ngôn ngữ', 'text' => 'Mở rộng tiếng Anh, Trung hoặc ngôn ngữ khác khi cần.'],
            ['icon' => 'fa-solid fa-chart-line', 'title' => 'SEO nền tảng', 'text' => 'Heading, schema, sitemap, tốc độ và cấu trúc URL được chuẩn bị từ đầu.'],
            ['icon' => 'fa-solid fa-user-gear', 'title' => 'Quản trị dễ dùng', 'text' => 'Tự cập nhật bài viết, dịch vụ, dự án và thông tin liên hệ.'],
            ['icon' => 'fa-solid fa-headset', 'title' => 'Hỗ trợ sau bàn giao', 'text' => 'Có gói hosting, bảo trì, đăng bài và SEO định kỳ.'],
        ],
        'packages' => [
            ['name' => 'Khởi đầu', 'price' => 'Từ 8 triệu', 'desc' => 'Website giới thiệu gọn, đủ trang cơ bản.', 'items' => ['Giao diện tùy chỉnh', 'Trang nội dung cơ bản', 'Form và bản đồ', 'SEO kỹ thuật nền tảng']],
            ['name' => 'Tăng trưởng', 'price' => 'Từ 15 triệu', 'desc' => 'Cấu trúc chuyên sâu cho bán hàng và nội dung.', 'items' => ['Thiết kế riêng theo ngành', 'Dự án và hồ sơ năng lực', 'Landing page dịch vụ', 'Tracking và kế hoạch nội dung'], 'featured' => true],
            ['name' => 'Đa ngôn ngữ', 'price' => 'Báo giá riêng', 'desc' => 'Dành cho doanh nghiệp xuất khẩu hoặc nhiều thị trường.', 'items' => ['Nhiều ngôn ngữ', 'Danh mục sản phẩm lớn', 'Phân quyền nội dung', 'Tích hợp theo nhu cầu']],
        ],
        'faqs' => [
            ['q' => 'Website doanh nghiệp cần chuẩn bị những nội dung gì?', 'a' => 'Tối thiểu gồm thông tin giới thiệu, sản phẩm hoặc dịch vụ, năng lực nổi bật, hình ảnh thực tế, dự án và thông tin liên hệ. WebApp Bắc Ninh sẽ gửi danh sách dữ liệu cần chuẩn bị theo từng trang.'],
            ['q' => 'Có thể làm trước tiếng Việt rồi bổ sung tiếng Anh sau không?', 'a' => 'Có. Cấu trúc có thể được chuẩn bị sẵn để bổ sung ngôn ngữ ở giai đoạn sau mà không phải làm lại toàn bộ giao diện.'],
            ['q' => 'Website có dùng để gửi hồ sơ năng lực cho khách hàng được không?', 'a' => 'Có. Website được tổ chức để đội kinh doanh có thể gửi từng đường dẫn sản phẩm, dự án hoặc năng lực thay cho việc gửi nhiều file rời.'],
        ],
    ],
    'ecommerce' => [
        'route' => 'website-ban-hang.php',
        'slug' => 'website-ban-hang',
        'menu_key' => 'ecommerce',
        'eyebrow' => 'WEBSITE BÁN HÀNG',
        'title' => 'Website bán hàng dễ quản lý, thuận tiện cho khách đặt mua',
        'highlight' => 'Tập trung sản phẩm, đơn hàng và dữ liệu khách hàng về một nơi.',
        'description' => 'Phù hợp cửa hàng, nhà phân phối và doanh nghiệp muốn chủ động kênh bán hàng thay vì phụ thuộc hoàn toàn vào mạng xã hội hoặc sàn thương mại điện tử.',
        'meta_title' => 'Thiết kế website bán hàng tại Bắc Ninh | WebApp Bắc Ninh',
        'meta_description' => 'Thiết kế website bán hàng tại Bắc Ninh với danh mục sản phẩm, giỏ hàng, đơn hàng, thanh toán, vận chuyển và quản trị dễ sử dụng.',
        'image' => 'assets/images/project-ecommerce.webp',
        'secondary_image' => 'assets/images/seo-operation.webp',
        'icon' => 'fa-solid fa-cart-shopping',
        'price_from' => 'Từ 15 triệu',
        'timeline' => '3 - 6 tuần',
        'cta' => 'Nhận tư vấn website bán hàng',
        'need_value' => 'Thiết kế website bán hàng',
        'audiences' => [
            'Cửa hàng muốn nhận đơn trực tiếp trên website',
            'Nhà phân phối có nhiều nhóm sản phẩm và bảng giá',
            'Doanh nghiệp đang bán trên Facebook, Zalo hoặc sàn',
            'Thương hiệu cần quản lý dữ liệu khách hàng và nội dung riêng',
        ],
        'problems' => [
            ['icon' => 'fa-solid fa-comments-dollar', 'title' => 'Chốt đơn thủ công', 'text' => 'Nhân viên phải hỏi lại mã hàng, giá, số lượng và thông tin giao hàng qua tin nhắn.'],
            ['icon' => 'fa-solid fa-boxes-stacked', 'title' => 'Sản phẩm khó tìm', 'text' => 'Danh mục lớn nhưng thiếu bộ lọc, tìm kiếm và cách trình bày thông tin rõ ràng.'],
            ['icon' => 'fa-solid fa-database', 'title' => 'Dữ liệu phân tán', 'text' => 'Đơn hàng và khách hàng nằm ở nhiều kênh, khó theo dõi và chăm sóc lại.'],
        ],
        'pages' => ['Trang chủ bán hàng', 'Danh mục sản phẩm', 'Chi tiết sản phẩm', 'Giỏ hàng', 'Đặt hàng', 'Tra cứu đơn', 'Khuyến mại / Tin tức', 'Liên hệ'],
        'features' => [
            ['icon' => 'fa-solid fa-box-open', 'title' => 'Quản lý sản phẩm', 'text' => 'Danh mục, thuộc tính, giá, hình ảnh và trạng thái sản phẩm.'],
            ['icon' => 'fa-solid fa-cart-arrow-down', 'title' => 'Giỏ hàng và đặt hàng', 'text' => 'Quy trình mua hàng gọn trên cả điện thoại và máy tính.'],
            ['icon' => 'fa-solid fa-credit-card', 'title' => 'Thanh toán', 'text' => 'Có thể tích hợp QR, chuyển khoản hoặc cổng thanh toán.'],
            ['icon' => 'fa-solid fa-truck-fast', 'title' => 'Vận chuyển', 'text' => 'Cấu hình phí giao hàng hoặc tích hợp đơn vị vận chuyển khi cần.'],
            ['icon' => 'fa-solid fa-receipt', 'title' => 'Quản lý đơn', 'text' => 'Theo dõi trạng thái, thông tin khách và lịch sử xử lý đơn hàng.'],
            ['icon' => 'fa-solid fa-chart-column', 'title' => 'Theo dõi chuyển đổi', 'text' => 'Gắn Analytics, Pixel và các sự kiện mua hàng quan trọng.'],
        ],
        'packages' => [
            ['name' => 'Catalog', 'price' => 'Từ 12 triệu', 'desc' => 'Trưng bày sản phẩm, nhận yêu cầu báo giá.', 'items' => ['Danh mục sản phẩm', 'Tìm kiếm cơ bản', 'Form báo giá', 'Quản trị nội dung']],
            ['name' => 'Bán hàng', 'price' => 'Từ 18 triệu', 'desc' => 'Đủ giỏ hàng, đặt hàng và quản lý đơn.', 'items' => ['Giỏ hàng và checkout', 'Quản lý đơn hàng', 'Mã giảm giá cơ bản', 'Thông báo đơn mới'], 'featured' => true],
            ['name' => 'Theo nghiệp vụ', 'price' => 'Báo giá riêng', 'desc' => 'Tích hợp kho, thanh toán, vận chuyển hoặc hệ thống khác.', 'items' => ['API và đồng bộ', 'Phân quyền nâng cao', 'Nhiều kho / chi nhánh', 'Báo cáo theo yêu cầu']],
        ],
        'faqs' => [
            ['q' => 'Website bán hàng có bắt buộc tích hợp thanh toán online không?', 'a' => 'Không. Có thể bắt đầu bằng đặt hàng và chuyển khoản, sau đó bổ sung cổng thanh toán khi lượng đơn và quy trình đã ổn định.'],
            ['q' => 'Có nhập sản phẩm từ Excel được không?', 'a' => 'Có thể xây chức năng nhập dữ liệu tùy theo cấu trúc sản phẩm. Cần xem trước file Excel để xác định trường dữ liệu và cách xử lý ảnh.'],
            ['q' => 'Website có kết nối phần mềm bán hàng hoặc kho không?', 'a' => 'Có thể tích hợp nếu phần mềm hiện tại có API hoặc cơ chế xuất nhập dữ liệu phù hợp. Phần này được khảo sát và báo giá riêng.'],
        ],
    ],
    'landing' => [
        'route' => 'landing-page.php',
        'slug' => 'landing-page',
        'menu_key' => 'landing',
        'eyebrow' => 'LANDING PAGE CHUYỂN ĐỔI',
        'title' => 'Landing page tập trung một mục tiêu và một hành động chính',
        'highlight' => 'Dùng cho quảng cáo, tuyển sinh, sự kiện và dịch vụ trọng điểm.',
        'description' => 'Một trang đích được xây theo luồng thuyết phục rõ ràng, giúp khách hàng hiểu lợi ích, xem bằng chứng và để lại thông tin hoặc liên hệ ngay.',
        'meta_title' => 'Thiết kế landing page tại Bắc Ninh | WebApp Bắc Ninh',
        'meta_description' => 'Thiết kế landing page tại Bắc Ninh cho quảng cáo, tuyển sinh, sự kiện, ra mắt sản phẩm và dịch vụ. Tối ưu mobile, form lead và tracking.',
        'image' => 'assets/images/project-landing.webp',
        'secondary_image' => 'assets/images/project-tour.webp',
        'icon' => 'fa-solid fa-bullseye',
        'price_from' => 'Từ 6,5 triệu',
        'timeline' => '7 - 15 ngày',
        'cta' => 'Nhận bố cục landing page',
        'need_value' => 'Thiết kế landing page',
        'audiences' => [
            'Chiến dịch chạy quảng cáo Facebook hoặc Google',
            'Sự kiện, hội thảo, tuyển sinh và đăng ký tham dự',
            'Ra mắt sản phẩm hoặc dịch vụ mới',
            'Doanh nghiệp cần thử nghiệm thị trường trước khi làm website lớn',
        ],
        'problems' => [
            ['icon' => 'fa-solid fa-arrow-up-right-dots', 'title' => 'Chi phí quảng cáo cao', 'text' => 'Khách bấm quảng cáo nhưng trang đích không đúng thông điệp hoặc quá nhiều lựa chọn.'],
            ['icon' => 'fa-solid fa-route', 'title' => 'Luồng nội dung yếu', 'text' => 'Thông tin thiếu thứ tự, không xử lý phản đối và chưa tạo động lực hành động.'],
            ['icon' => 'fa-solid fa-filter-circle-xmark', 'title' => 'Không đo được lead', 'text' => 'Thiếu form, sự kiện tracking và nguồn chiến dịch để đánh giá hiệu quả.'],
        ],
        'pages' => ['Hero và CTA', 'Vấn đề khách hàng', 'Giải pháp / Lợi ích', 'Dịch vụ / Sản phẩm', 'Bằng chứng / Dự án', 'Bảng giá', 'FAQ', 'Form đăng ký'],
        'features' => [
            ['icon' => 'fa-solid fa-pen-nib', 'title' => 'Bố cục bán hàng', 'text' => 'Sắp xếp nội dung theo hành trình ra quyết định của khách hàng.'],
            ['icon' => 'fa-solid fa-mobile-button', 'title' => 'Mobile-first', 'text' => 'Ưu tiên tốc độ đọc, nút CTA và form trên điện thoại.'],
            ['icon' => 'fa-solid fa-wand-magic-sparkles', 'title' => 'Hiệu ứng vừa đủ', 'text' => 'Chuyển động hỗ trợ trải nghiệm, không làm trang nặng hoặc rối.'],
            ['icon' => 'fa-solid fa-list-check', 'title' => 'Form thu lead', 'text' => 'Biểu mẫu ngắn, rõ và có thể lưu hoặc gửi thông báo.'],
            ['icon' => 'fa-solid fa-chart-simple', 'title' => 'Tracking chiến dịch', 'text' => 'Gắn Analytics, Pixel, UTM và sự kiện chuyển đổi.'],
            ['icon' => 'fa-solid fa-flask', 'title' => 'Dễ thử nghiệm', 'text' => 'Có thể thay CTA, tiêu đề hoặc gói giá để tối ưu sau khi chạy.'],
        ],
        'packages' => [
            ['name' => 'Landing cơ bản', 'price' => 'Từ 6,5 triệu', 'desc' => 'Một trang đích rõ thông tin và form đăng ký.', 'items' => ['Thiết kế responsive', 'Tối đa 8 section', 'Form lead', 'SEO và chia sẻ cơ bản']],
            ['name' => 'Landing quảng cáo', 'price' => 'Từ 9 triệu', 'desc' => 'Tập trung chuyển đổi và đo lường chiến dịch.', 'items' => ['Nội dung theo hành trình', 'Tracking và UTM', 'CTA cố định', 'Tối ưu tốc độ'], 'featured' => true],
            ['name' => 'Landing nâng cao', 'price' => 'Báo giá riêng', 'desc' => 'Có tính toán, booking, thanh toán hoặc chức năng riêng.', 'items' => ['Logic biểu mẫu', 'Tích hợp API', 'Thanh toán / đặt lịch', 'Dashboard dữ liệu']],
        ],
        'faqs' => [
            ['q' => 'Landing page khác website thông thường ở điểm nào?', 'a' => 'Landing page tập trung vào một chiến dịch và một hành động chính, trong khi website có nhiều nhóm nội dung và phục vụ hoạt động dài hạn.'],
            ['q' => 'Có hỗ trợ viết nội dung landing page không?', 'a' => 'Có thể hỗ trợ xây khung nội dung, biên tập thông điệp và CTA. Mức độ viết mới hoàn toàn sẽ được xác định theo dữ liệu doanh nghiệp cung cấp.'],
            ['q' => 'Landing page có chạy độc lập với website hiện tại được không?', 'a' => 'Có. Landing page có thể đặt trên tên miền riêng, tên miền phụ hoặc một đường dẫn trong website hiện tại.'],
        ],
    ],
    'redesign' => [
        'route' => 'thiet-ke-lai-website.php',
        'slug' => 'thiet-ke-lai-website',
        'menu_key' => 'redesign',
        'eyebrow' => 'THIẾT KẾ LẠI WEBSITE CŨ',
        'title' => 'Làm lại website cũ nhưng giữ phần dữ liệu còn giá trị',
        'highlight' => 'Cải thiện giao diện, tốc độ, quản trị và khả năng tạo khách hàng.',
        'description' => 'Không phải lúc nào cũng cần bỏ toàn bộ website. WebApp Bắc Ninh kiểm tra cấu trúc, nội dung, dữ liệu và hệ thống hiện tại để đề xuất phần nên giữ, phần cần thay và cách chuyển đổi an toàn.',
        'meta_title' => 'Thiết kế lại website cũ tại Bắc Ninh | WebApp Bắc Ninh',
        'meta_description' => 'Dịch vụ thiết kế lại website cũ tại Bắc Ninh: nâng cấp giao diện, mobile, tốc độ, SEO, quản trị và chuyển dữ liệu an toàn.',
        'image' => 'assets/images/project-software.webp',
        'secondary_image' => 'assets/images/hero-industrial.webp',
        'icon' => 'fa-solid fa-arrows-rotate',
        'price_from' => 'Khảo sát trước',
        'timeline' => '2 - 6 tuần',
        'cta' => 'Yêu cầu kiểm tra website cũ',
        'need_value' => 'Thiết kế lại website cũ',
        'audiences' => [
            'Website đã dùng nhiều năm và giao diện lỗi thời',
            'Trang tải chậm, lỗi mobile hoặc thường xuyên phát sinh lỗi',
            'Khu vực quản trị khó dùng, không cập nhật được nội dung',
            'Website có dữ liệu SEO hoặc bài viết cần giữ lại khi nâng cấp',
        ],
        'problems' => [
            ['icon' => 'fa-solid fa-gauge-high', 'title' => 'Tốc độ và trải nghiệm kém', 'text' => 'Mã nguồn cũ, ảnh nặng, plugin dư thừa hoặc bố cục không còn phù hợp thiết bị mới.'],
            ['icon' => 'fa-solid fa-triangle-exclamation', 'title' => 'Rủi ro mất dữ liệu', 'text' => 'Làm mới thiếu kế hoạch có thể mất bài viết, URL cũ, thứ hạng và thông tin khách hàng.'],
            ['icon' => 'fa-solid fa-screwdriver-wrench', 'title' => 'Khó bảo trì', 'text' => 'Không rõ đơn vị cũ, source thiếu hoặc hệ thống phụ thuộc nhiều thành phần lỗi thời.'],
        ],
        'pages' => ['Kiểm tra hiện trạng', 'Sao lưu dữ liệu', 'Thiết kế giao diện mới', 'Chuyển nội dung', 'Redirect URL cũ', 'Kiểm thử form và chức năng', 'Theo dõi sau chuyển đổi'],
        'features' => [
            ['icon' => 'fa-solid fa-magnifying-glass', 'title' => 'Audit website cũ', 'text' => 'Kiểm tra giao diện, nội dung, tốc độ, SEO, hosting và mã nguồn.'],
            ['icon' => 'fa-solid fa-database', 'title' => 'Giữ dữ liệu quan trọng', 'text' => 'Lập kế hoạch sao lưu và chuyển bài viết, sản phẩm, khách hàng khi có thể.'],
            ['icon' => 'fa-solid fa-link', 'title' => 'Bảo toàn URL', 'text' => 'Giữ đường dẫn có giá trị hoặc thiết lập redirect phù hợp.'],
            ['icon' => 'fa-solid fa-mobile-screen-button', 'title' => 'Giao diện responsive mới', 'text' => 'Thiết kế lại theo nội dung và mục tiêu kinh doanh hiện tại.'],
            ['icon' => 'fa-solid fa-shield-halved', 'title' => 'Kiểm thử trước khi chuyển', 'text' => 'Chạy bản mới trên môi trường thử nghiệm và có phương án quay lại.'],
            ['icon' => 'fa-solid fa-chart-line', 'title' => 'Theo dõi sau nâng cấp', 'text' => 'Kiểm tra lỗi 404, Search Console, form và tốc độ sau khi đưa vào sử dụng.'],
        ],
        'packages' => [
            ['name' => 'Làm mới giao diện', 'price' => 'Từ 10 triệu', 'desc' => 'Giữ nền tảng hiện tại nếu mã nguồn còn phù hợp.', 'items' => ['Thiết kế giao diện mới', 'Responsive', 'Tối ưu trang chính', 'Kiểm tra chức năng cũ']],
            ['name' => 'Xây lại có chuyển dữ liệu', 'price' => 'Từ 18 triệu', 'desc' => 'Dùng nền tảng mới và chuyển phần dữ liệu còn giá trị.', 'items' => ['Audit và backup', 'Phát triển website mới', 'Chuyển dữ liệu', 'Redirect và kiểm thử'], 'featured' => true],
            ['name' => 'Hệ thống phức tạp', 'price' => 'Báo giá riêng', 'desc' => 'Website bán hàng, thành viên hoặc có tích hợp nghiệp vụ.', 'items' => ['Phân tích database', 'Chuyển đổi theo giai đoạn', 'API và tích hợp', 'Kế hoạch downtime']],
        ],
        'faqs' => [
            ['q' => 'Làm lại website có mất thứ hạng Google không?', 'a' => 'Có rủi ro nếu thay URL và nội dung thiếu kế hoạch. Vì vậy cần lập danh sách URL cũ, giữ nội dung có giá trị, thiết lập redirect và theo dõi Search Console sau khi chuyển.'],
            ['q' => 'Có giữ lại bài viết và sản phẩm cũ được không?', 'a' => 'Thông thường có thể, nhưng phụ thuộc mã nguồn, cấu trúc database và chất lượng dữ liệu hiện tại. Cần kiểm tra trước khi cam kết phạm vi chuyển.'],
            ['q' => 'Website cũ vẫn hoạt động trong lúc làm bản mới chứ?', 'a' => 'Có. Bản mới nên được phát triển trên môi trường riêng. Chỉ chuyển sang bản mới sau khi đã kiểm thử và có bản sao lưu đầy đủ.'],
        ],
    ],
];
