<main>
  <section class="inner-hero inner-hero--pricing">
    <div class="container"><div class="row align-items-center gy-4">
      <div class="col-lg-7" data-aos="fade-up"><nav class="inner-breadcrumb"><a href="<?= e(frontend_url('index.php')) ?>">Trang chủ</a><i class="fa-solid fa-angle-right"></i><span>Bảng giá</span></nav><span class="section-kicker">CHI PHÍ RÕ THEO PHẠM VI</span><h1>Bảng giá website và dịch vụ duy trì</h1><p>Giá tham khảo giúp doanh nghiệp chọn điểm bắt đầu. Chi phí cuối cùng được xác định sau khi thống nhất số trang, nội dung, chức năng và tiến độ.</p><div class="inner-hero__actions"><a class="btn btn-primary btn-lg" href="#websitePricing">Xem gói website</a><a class="btn btn-outline-dark btn-lg" href="#pricingContact">Nhận báo giá riêng</a></div></div>
      <div class="col-lg-5" data-aos="fade-left"><div class="hero-summary"><div><i class="fa-solid fa-file-signature"></i><strong>Phạm vi rõ</strong><span>Chốt đầu việc trước khi triển khai</span></div><div><i class="fa-solid fa-layer-group"></i><strong>Có thể chia giai đoạn</strong><span>Ưu tiên phần cần dùng trước</span></div><div><i class="fa-solid fa-headset"></i><strong>Có gói duy trì</strong><span>Không bỏ khách sau bàn giao</span></div></div></div>
    </div></div>
  </section>

  <section class="section section--cream" id="websitePricing"><div class="container"><div class="section-heading text-center"><span class="section-kicker">THIẾT KẾ WEBSITE</span><h2>Ba mức triển khai phổ biến</h2><p>Không tính giá theo số hiệu ứng. Mỗi gói được xác định theo mục tiêu và phạm vi sử dụng.</p></div><div class="pricing-grid">
    <article class="price-card" data-aos="fade-up"><div class="price-card__head"><span>GÓI KHỞI ĐẦU</span><h3>Website giới thiệu cơ bản</h3><p>Phù hợp doanh nghiệp mới cần hiện diện chuyên nghiệp và dễ quản trị.</p></div><div class="price-card__price"><small>Từ</small><strong>8 triệu</strong></div><ul><li>Thiết kế theo nhận diện cơ bản</li><li>Trang chủ và 5–7 trang nội dung</li><li>Quản trị dịch vụ, bài viết, hình ảnh</li><li>Responsive, form, bản đồ</li><li>SEO kỹ thuật nền tảng</li><li>Hướng dẫn và bảo hành</li></ul><a class="btn btn-outline-primary w-100" href="#pricingContact">Nhận phạm vi chi tiết</a></article>
    <article class="price-card price-card--featured" data-aos="fade-up" data-aos-delay="70"><div class="price-card__badge">PHỔ BIẾN</div><div class="price-card__head"><span>GÓI TĂNG TRƯỞNG</span><h3>Website bán hàng và tạo lead</h3><p>Phù hợp doanh nghiệp dùng website làm nền tảng marketing và kinh doanh.</p></div><div class="price-card__price"><small>Từ</small><strong>15 triệu</strong></div><ul><li>Thiết kế riêng theo ngành</li><li>Dịch vụ, dự án, bài viết chuyên sâu</li><li>Landing page dịch vụ trọng điểm</li><li>Tracking và Search Console</li><li>Tối ưu tốc độ và chuyển đổi</li><li>Hỗ trợ vận hành sau bàn giao</li></ul><a class="btn btn-primary w-100" href="#pricingContact">Tư vấn gói phù hợp</a></article>
    <article class="price-card" data-aos="fade-up" data-aos-delay="140"><div class="price-card__head"><span>GÓI THEO YÊU CẦU</span><h3>Website có nghiệp vụ riêng</h3><p>Bán hàng, đa ngôn ngữ, nhiều chi nhánh, tích hợp hoặc chức năng riêng.</p></div><div class="price-card__price"><small>Khảo sát</small><strong>Báo giá riêng</strong></div><ul><li>Sản phẩm và đơn hàng nâng cao</li><li>Thanh toán, vận chuyển, API</li><li>Phân quyền quản trị</li><li>Đa ngôn ngữ hoặc nhiều đơn vị</li><li>Chia giai đoạn triển khai</li><li>Tài liệu phạm vi và nghiệm thu</li></ul><a class="btn btn-outline-primary w-100" href="#pricingContact">Đặt lịch khảo sát</a></article>
  </div></div></section>

  <section class="section"><div class="container"><div class="row align-items-end gy-3 mb-5"><div class="col-lg-7"><span class="section-kicker">DỊCH VỤ BỔ SUNG</span><h2 class="section-title mb-0">Những hạng mục thường phát sinh</h2></div><div class="col-lg-5"><p class="section-lead mb-0">Báo tách riêng để doanh nghiệp biết mình đang đầu tư cho phần nào.</p></div></div><div class="addon-grid">
    <article><i class="fa-solid fa-language"></i><h3>Đa ngôn ngữ</h3><p>Cấu trúc nội dung riêng cho tiếng Việt, Anh, Trung hoặc ngôn ngữ khác.</p><strong>Từ 3 triệu</strong></article>
    <article><i class="fa-solid fa-cart-shopping"></i><h3>Giỏ hàng và đặt hàng</h3><p>Danh mục, sản phẩm, giỏ hàng, thông tin đơn và thông báo.</p><strong>Từ 5 triệu</strong></article>
    <article><i class="fa-solid fa-credit-card"></i><h3>Thanh toán và vận chuyển</h3><p>Kết nối cổng thanh toán, QR hoặc đơn vị vận chuyển phù hợp.</p><strong>Khảo sát tích hợp</strong></article>
    <article><i class="fa-solid fa-bullseye"></i><h3>Landing page bổ sung</h3><p>Trang chiến dịch riêng cho quảng cáo, sản phẩm hoặc dịch vụ mới.</p><strong>Từ 3 triệu</strong></article>
    <article><i class="fa-solid fa-database"></i><h3>Nhập dữ liệu ban đầu</h3><p>Đăng sản phẩm, bài viết, dự án và nội dung doanh nghiệp cung cấp.</p><strong>Theo khối lượng</strong></article>
    <article><i class="fa-solid fa-plug"></i><h3>API và chức năng riêng</h3><p>Kết nối CRM, Zalo, phần mềm quản lý hoặc hệ thống bên thứ ba.</p><strong>Báo giá riêng</strong></article>
  </div></div></section>

  <section class="section section--navy"><div class="container"><div class="section-heading text-center"><span class="section-kicker section-kicker--gold">CHI PHÍ DUY TRÌ</span><h2 class="section-title section-title--light">Website cần được chăm sóc sau khi bàn giao</h2><p>Chọn riêng từng dịch vụ hoặc dùng gói đồng hành theo tháng.</p></div><div class="monthly-price-grid">
    <article><span>01</span><h3>Website Care</h3><p>Hosting, backup, SSL, theo dõi hoạt động và hỗ trợ kỹ thuật.</p><strong>Từ 500.000đ/tháng</strong><small>Có gói theo năm</small></article>
    <article><span>02</span><h3>Content Website</h3><p>Đăng bài, sản phẩm, banner và cập nhật các trang nội dung.</p><strong>Từ 1.500.000đ/tháng</strong><small>Theo khối lượng nội dung</small></article>
    <article class="is-highlight"><span>03</span><h3>Website Growth</h3><p>Bảo trì, nội dung, SEO nền tảng, theo dõi dữ liệu và báo cáo.</p><strong>Từ 3.500.000đ/tháng</strong><small>Gói đồng hành</small></article>
  </div></div></section>

  <section class="section section--light"><div class="container"><div class="section-heading text-center"><span class="section-kicker">CÂU HỎI THƯỜNG GẶP</span><h2>Trước khi chốt ngân sách</h2></div><div class="accordion faq-accordion mx-auto" id="pricingFaq">
    <div class="accordion-item"><h3 class="accordion-header"><button class="accordion-button" data-bs-toggle="collapse" data-bs-target="#pf1">Giá đã gồm tên miền và hosting chưa?</button></h3><div id="pf1" class="accordion-collapse collapse show" data-bs-parent="#pricingFaq"><div class="accordion-body">Tùy gói. Báo giá sẽ tách rõ chi phí thiết kế, tên miền, hosting, SSL và dịch vụ duy trì để doanh nghiệp dễ theo dõi.</div></div></div>
    <div class="accordion-item"><h3 class="accordion-header"><button class="accordion-button collapsed" data-bs-toggle="collapse" data-bs-target="#pf2">Có phát sinh ngoài báo giá không?</button></h3><div id="pf2" class="accordion-collapse collapse" data-bs-parent="#pricingFaq"><div class="accordion-body">Không phát sinh nếu phạm vi không thay đổi. Hạng mục bổ sung sẽ được báo và xác nhận trước khi thực hiện.</div></div></div>
    <div class="accordion-item"><h3 class="accordion-header"><button class="accordion-button collapsed" data-bs-toggle="collapse" data-bs-target="#pf3">Có thể chia thanh toán theo tiến độ không?</button></h3><div id="pf3" class="accordion-collapse collapse" data-bs-parent="#pricingFaq"><div class="accordion-body">Có. Dự án có thể chia thành các mốc khởi động, duyệt giao diện, hoàn thiện chức năng và bàn giao.</div></div></div>
  </div></div></section>

  <?php echo view('frontend.site.components.lead-form', ['sectionId'=>'pricingContact','title'=>'Nhận báo giá theo đúng nhu cầu','description'=>'Gửi loại website, ngành nghề và ngân sách dự kiến. WebApp Bắc Ninh sẽ đề xuất phạm vi phù hợp thay vì ép vào một gói cứng.','needValue'=>'Tư vấn bảng giá']); ?>
</main>

