<div class="secondary-content"><main id="main"><div x-data="catalog()" data-catalog><section class="hero "><div class="container hero-inner"><div class="hero-copy"><div class="breadcrumb"><a href="/">Trang chủ</a><svg class="icon " width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m9 5 7 7-7 7"/></svg><span>Tin tức</span></div><h1>Tin tức & Kiến thức<br><span>Đồng hành</span> cùng doanh nghiệp</h1><p>Chia sẻ kiến thức hữu ích về website, phần mềm, marketing<br class="desktop-br"> và vận hành số, giúp doanh nghiệp bắt kịp xu hướng và phát triển bền vững.</p><div class="hero-search"><input type="search" aria-label="Tìm bài viết" placeholder="Tìm kiếm bài viết, chủ đề bạn quan tâm..." data-search x-model.debounce.150ms="query"><button aria-label="Tìm kiếm"><svg class="icon " width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg></button></div></div><div class="hero-art"><img class="" src="/frontend/interface/images/news-hero.webp" alt="Tin tức — WebApp Bắc Ninh" loading="eager" decoding="async"></div></div><div class="container hero-filters">@include('frontend.interface.catalog-filters')</div></section><section class="section "><div class="container"><div class="section-heading"><div><h2>Bài viết nổi bật</h2><p>Những bài viết được quan tâm nhất, mang đến góc nhìn thực tế và giá trị ứng dụng cho doanh nghiệp.</p></div><a class="text-link" href="#bai-viet">Xem tất cả bài viết <svg class="icon " width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M5 12h14m-5-5 5 5-5 5"/></svg></a></div><div class="news-featured grid grid-cols-1 lg:grid-cols-2 gap-6">@if (isset($catalogItems[0]))
<article class="card article featured-main">
<img src="{{ $catalogItems[0]['image_url'] }}" alt="{{ $catalogItems[0]['title'] }}" loading="lazy">
<div class="card-body"><span class="image-tag">{{ $catalogItems[0]['category_label'] }}</span><h2>{{ $catalogItems[0]['title'] }}</h2><p>{{ $catalogItems[0]['excerpt'] }}</p><a class="btn btn-primary" href="{{ route('articles.show', $catalogItems[0]['slug']) }}">Xem chi tiết →</a></div></article>
@endif<div class="featured-side">@if (isset($catalogItems[1]))
@include('frontend.interface.catalog-card', ['item' => $catalogItems[1], 'catalogType' => 'articles'])
@endif@if (isset($catalogItems[2]))
@include('frontend.interface.catalog-card', ['item' => $catalogItems[2], 'catalogType' => 'articles'])
@endif</div></div></div></section><section class="section "><div class="container"><div class="section-heading"><div><h2>Bài viết mới nhất</h2><p>Cập nhật những kiến thức, xu hướng và kinh nghiệm mới nhất về website, phần mềm và chuyển đổi số.</p></div></div><div id="bai-viet" class="cards-grid grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">@foreach ($catalogItems as $item)
@include('frontend.interface.catalog-card', ['catalogType' => 'articles'])
@endforeach</div><p class="empty-state" data-empty hidden>Không có bài viết phù hợp. Hãy đổi từ khóa hoặc danh mục.</p></div></section></div><section class="container newsletter"><div class="newsletter-title"><svg class="icon " width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="2" y="4" width="20" height="16" rx="2"/><path d="m2 5 10 8 10-8"/></svg><div><h2>Nhận thêm kiến thức hữu ích mỗi tuần</h2><p>Đăng ký email để nhận các bài viết mới nhất, xu hướng công nghệ và kinh nghiệm thực tế.</p></div></div><a class="btn btn-primary" href="/lien-he">Trao đổi với chúng tôi →</a></section><section class="container cta"><div><h2>Sẵn sàng bắt đầu dự án của bạn ngay hôm nay?</h2><p>Chúng tôi luôn sẵn sàng tư vấn và đồng hành cùng doanh nghiệp của bạn.</p></div><div class="actions"><a class="btn btn-primary" href="/lien-he">Nhận tư vấn miễn phí<svg class="icon " width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M5 12h14m-5-5 5 5-5 5"/></svg></a><a class="btn btn-outline" href="/san-pham">Xem Demo</a></div></section></main></div>